#!/usr/bin/env python
# Added by Chaobin Tang <chaobin.py@gmail.com>

'''
Questions App Settings
'''


QUESTION_MAX_LENGTH = 2000
CHOICE_MAX = 8
FORM_TAG_LIST_MAX_LENGTH = 500
FORM_QUESTIONNAIRE_NAME_MAX_LENGTH = 500
FORM_QUESTIONNAIRE_DESC_MAX_LENGTH = 2000
QUESTIONS_PER_PAGE = 10
QUESTIONNAIRES_PER_PAGE = 20
REGISTER_QUESTION_INTO_ADMIN = True
